### ISSUE TITLE
"Getting started" section across all operators

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#237]
We've decided that it would be good for onboarding new users to have a dedicated "Getting started" section in all operators.

It should contain
- an "Install" page with instructions for how to install using either stackablectl or Helm
- a "First steps" page with instructions on how to deploy an instance and verify that it is up, ideally with a simple task to do

This also relates to #204 - we should mention stackablectl in the install page (not done currently)

All the script and yaml files in there should be put into a shell script that can actually be executed, for testing purposes. Have a look at the druid docs, where this has been implemented already: https://github.com/stackabletech/druid-operator/tree/main/docs/modules/getting_started

- [x] Airflow - https://github.com/stackabletech/airflow-operator/issues/142
- [x] Druid - https://github.com/stackabletech/druid-operator/pull/278
- [x] HBase - https://github.com/stackabletech/hbase-operator/issues/227
- [x] HDFS - https://github.com/stackabletech/hdfs-operator/issues/220
- [x] Hive - https://github.com/stackabletech/hive-operator/issues/224
- [x] Kafka - https://github.com/stackabletech/kafka-operator/issues/447
- [x] NiFi - https://github.com/stackabletech/nifi-operator/issues/325
- [x] OPA - https://github.com/stackabletech/opa-operator/issues/329
- [x] Spark - WIP - https://github.com/stackabletech/spark-k8s-operator/issues/113
- [x] Superset - https://github.com/stackabletech/superset-operator/pull/246
- [x] Trino - https://github.com/stackabletech/trino-operator/issues/253
- [x] ZooKeeper - https://github.com/stackabletech/zookeeper-operator/issues/536

Secret and Commons Operator don't need a Getting Started guide.

----

Acceptance criteria per operator:
- [ ] a new module `getting_started` exists, with an `index.adoc`, a `installation.adoc` and `first_steps.adoc`
- [ ] The old `installation.adoc` is removed.
- [ ] All the `yaml` and shell snippets are in the `examples/code` directory and can be executed as a script, to test the documentation
- [ ] versions to install are templated using the `template_docs.sh` script and the `templating_vars.yaml` file.
- [ ] Any example files that are incorporated into the getting started guide are removed from the examples directory (because there they are not tested, with the new script they will be tested).

**Comment by fhennig** [comment]
As part of this, we can also tackle this ticket: https://github.com/stackabletech/issues/issues/239

**Comment by fhennig** [comment]
Update: The Druid docs were merged.

- All the code & scripts in the Getting Started guide is in an actual script that is testable
- There's a small templating script for templating in the docs now.

**Comment by maltesander** [comment]
All done!
