### ISSUE TITLE
Operator overview pages

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#282]
Explain for every operator:
- which roles does it have and what do they mean?
- Which resources does it create:
    -  i.e. statefulsets per role
    - configmap for discovery
 - also a diagram
- which resources does it tear down again?
    - for example, ConfigMaps and PVCs are staying
- what are the dependencies, what other operators does it connect to?
- link to demos

Steps:
- [x] Spike for one operator: https://github.com/stackabletech/druid-operator/pull/360
- [x] Then bring it to all operators

Operators:

Merged pre-23.4:

- [x] Airflow https://github.com/stackabletech/airflow-operator/pull/260
- [x] Druid https://github.com/stackabletech/druid-operator/pull/360
- [x] Kafka https://github.com/stackabletech/kafka-operator/pull/573
- [x] NiFi https://github.com/stackabletech/nifi-operator/pull/460
- [x] Spark https://github.com/stackabletech/spark-k8s-operator/pull/229
- [x] Superset https://github.com/stackabletech/superset-operator/pull/344
- [x] Trino https://github.com/stackabletech/trino-operator/pull/411
- [x] HBase https://github.com/stackabletech/hbase-operator/pull/344 (backported)

---

Part 2 (outstanding Operators): https://github.com/stackabletech/documentation/issues/408 (not everything got done in 23.4 and then priorities shifted)

**Comment by fhennig** [comment]
I've drafted a diagram for Druid in this branch: https://github.com/stackabletech/druid-operator/pull/360

**Comment by fhennig** [comment]
I'm putting this ticket back into "ready for work" because I wanna get working on the EDC a bit

**Comment by lfrancke** [comment]
You put it to "Done", was that intentional?

**Comment by fhennig** [comment]
Yep, I made #408 with some more work that needs to be done, but since I've switched to working on the EDC operator it was on hold and I wanted to get it off the board.
