### ISSUE TITLE
Document operator system requirements

### ISSUE THREAD

**Issue by maltesander** [stackabletech/documentation#289]
This is part of https://github.com/stackabletech/documentation/issues/247. We want to know the minimal and recommended requirements in terms of CPU,  memory and disk space for all operators. This should be documented (versioned) for each release.

~~This includes research / testing to find the minimal/recommended requirements to run the operator. What kind of load (e.g. reconciling 1000 clusters) can it withstand and what are the CPU and memory spikes under load.~~

This should be proven for local clusters like e.g. kind and managed Kubernetes. An approximation like 1 core and 1 GB of memory is sufficient.

## Acceptance

- [x] There exists a new page in the docs documenting the minimal/recommended requirements for each operator
- [ ] This must include a table containing the operator name, minimal/recommended CPU / memory / disk consumption as well as (if available) recommendations for optimal performance etc.

#### Tasks
- [x] Airflow : https://github.com/stackabletech/airflow-operator/pull/204
- [x] Druid : https://github.com/stackabletech/druid-operator/pull/354
- [x] HBase : https://github.com/stackabletech/hbase-operator/pull/284
- [x] Hadoop HDFS : https://github.com/stackabletech/hdfs-operator/pull/283
- [x] Hive : https://github.com/stackabletech/hive-operator/pull/278
- [x] Kafka : https://github.com/stackabletech/kafka-operator/pull/525
- [x] NiFi : https://github.com/stackabletech/nifi-operator/pull/392
- [x] Spark : https://github.com/stackabletech/spark-k8s-operator/pull/184
- [x] Superset : https://github.com/stackabletech/superset-operator/pull/301
- [x] Trino : https://github.com/stackabletech/trino-operator/pull/354
- [x] ZooKeeper : https://github.com/stackabletech/zookeeper-operator/issues/559

#### Tasks
- [x] Commons : https://github.com/stackabletech/commons-operator/pull/121
- [x] Listener : https://github.com/stackabletech/listener-operator/pull/37
- [x] OPA : https://github.com/stackabletech/opa-operator/pull/383
- [x] Secret : https://github.com/stackabletech/secret-operator/pull/218

### Documentation links

- [Airflow]( https://docs.stackable.tech/airflow/nightly/getting_started/index.html#_prerequisites)
- [Druid](https://docs.stackable.tech/druid/nightly/getting_started/index.html#_prerequisites)
- [HBase](https://docs.stackable.tech/hbase/nightly/getting_started/index.html#_prerequisites)
- [HDFS](https://docs.stackable.tech/hdfs/nightly/getting_started/index.html#_prerequisites)
- [Hive](https://docs.stackable.tech/hive/nightly/getting_started/index.html#_prerequisites)
- [Kafka](https://docs.stackable.tech/kafka/nightly/getting_started/index.html#_prerequisites)
- [NiFi](https://docs.stackable.tech/nifi/nightly/getting_started/index.html#_prerequisites)
- [Spark](https://docs.stackable.tech/spark-k8s/nightly/getting_started/index.html#_prerequisites)
- [Superset](https://docs.stackable.tech/superset/nightly/getting_started/index.html#_prerequisites)
- [ZooKeeper](https://docs.stackable.tech/zookeeper/nightly/getting_started/index.html#_prerequisites)
- [OPA](https://docs.stackable.tech/opa/nightly/getting_started/index.html#_prerequisites)
- [Commons](https://docs.stackable.tech/commons-operator/nightly/installation.html#_prerequisites)
- [Secret](https://docs.stackable.tech/secret-operator/nightly/installation.html#_prerequisites)
- [Listener](https://docs.stackable.tech/listener-operator/stable/installation.html#_prerequisites)

**Comment by teozkr** [comment]
What do you mean by min/max ranges here.. Absolute minimum vs recommended?

Especially CPU is also going to be really difficult to measure objectively. Not to mention that all of this depends heavily on the scale of the cluster.

**Comment by maltesander** [comment]
Yeah i changed max to recommended. 
I know its hard to measure, we just need minimal requirements (i think memory is more important here) that make sure for us the operator runs properly.
If we can get recommended values e.g. if your cluster is size x your should provide y resources. Or if you run 100 clusters of size x you should provide y resources.
The minimal requirements (e.g. assumption one cluster of size x) are more important as well (for liability).
For CPU i think we can use whatever CPU is e.g. on your laptop, in AWS / Azure etc. and give recommendations on what worked?

**Comment by lfrancke** [comment]
It is fine to "eyeball" this. We don't need it down to the Megabyte.
It is probably fine to say something along these lines: `We recommend at least 1Gb of RAM and 1 CPU core to run this operator"

The testing can be minimal. It would be good to understand if there is much queueing in kube-rs and if so if the queue size is configurable but don't spend too much time on this issue

**Comment by lfrancke** [comment]
FYI: It might very well be that this issue is already fully refined and all we need is issues for each operator. I can create those issues as soon as someone tells me that this is ready to go.

But I might also be wrong and some more refinement work is needed.
