### ISSUE TITLE
Document `listenerClass` usage in operators or global concepts page

### ISSUE THREAD

**Issue by maltesander** [stackabletech/documentation#393]
We currently do not document properly how our services are created.

After https://github.com/stackabletech/issues/issues/360 we do not create NodePorts per default, this changes the way users interacted with our products (you explicitly have to set the `listenerClass` if you want a NodePort).

This should be fixed in each operator, or a global concepts page should be created and linked to in each operator.

- [x] global concepts page updated: https://github.com/stackabletech/documentation/pull/446

```[tasklist]
### Tasks
- [x] Add docs for `listenerClass` in each operator
- [x] Fix comment in CRD to proper english
- [x] Adapt getting started guides and (if available) examples with `listenerClass` Nodeports
```

```[tasklist]
### Operators
- [ ] https://github.com/stackabletech/airflow-operator/pull/320
- [ ] https://github.com/stackabletech/druid-operator/pull/466
- [ ] https://github.com/stackabletech/hbase-operator/pull/390
- [ ] https://github.com/stackabletech/hdfs-operator/pull/387
- [ ] https://github.com/stackabletech/hive-operator/pull/367
- [x] Kafka -> Not configurable, only nodePort supported
- [ ] https://github.com/stackabletech/opa-operator/pull/471
- [ ] https://github.com/stackabletech/nifi-operator/pull/500
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/276
- [ ] https://github.com/stackabletech/superset-operator/pull/399
- [ ] https://github.com/stackabletech/trino-operator/pull/465
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/721
```

**Comment by lfrancke** [comment]
While we're at it we should look at the CRD level docs for the `listenerClass` as well as that doesn't seem to be entirely proper english.

**Comment by maltesander** [comment]
We should add the `listenerClass: external-unstable` in all getting started guides and examples as well. Otherwise you might install it but are not able to interact with the UI.

**Comment by lfrancke** [comment]
Maybe already done: https://docs.stackable.tech/home/stable/concepts/service-exposition.html
Check during refinement

**Comment by lfrancke** [comment]
Can this issue be closed?

**Comment by fhennig** [comment]
damnit! Yes, forgot it again ..
