### ISSUE TITLE
Link to feature tracker from the Operators

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#412]
We have the [feature tracker](https://features.stackable.tech/unified) which shows a complete overview of the features supported by each Operator. This is useful to the users, and we should link to it from each Operator landing page.

```[tasklist]
### Products
- [ ] https://github.com/stackabletech/airflow-operator/pull/420
- [ ] https://github.com/stackabletech/druid-operator/pull/543
- [ ] https://github.com/stackabletech/hbase-operator/pull/484
- [ ] https://github.com/stackabletech/hdfs-operator/pull/511
- [ ] https://github.com/stackabletech/hive-operator/pull/445
- [ ] https://github.com/stackabletech/kafka-operator/pull/691
- [ ] https://github.com/stackabletech/nifi-operator/pull/599
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/386
- [ ] https://github.com/stackabletech/superset-operator/pull/481
- [ ] https://github.com/stackabletech/trino-operator/pull/570
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/800
- [ ] https://github.com/stackabletech/opa-operator/pull/552
```
