### ISSUE TITLE
Add missing listener-operator documentation

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/documentation#480]
Add missing listener-operator documentation, e.g. to the documentation of stackablectl.
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/documentation/pull/486
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/146
- [ ] https://github.com/stackabletech/airflow-operator/pull/345
- [ ] https://github.com/stackabletech/druid-operator/pull/489
- [ ] https://github.com/stackabletech/hdfs-operator/pull/428
- [ ] https://github.com/stackabletech/hive-operator/pull/390
- [ ] https://github.com/stackabletech/kafka-operator/pull/641
- [ ] https://github.com/stackabletech/nifi-operator/pull/533
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/308
- [ ] https://github.com/stackabletech/superset-operator/pull/425
- [ ] https://github.com/stackabletech/trino-operator/pull/504
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/743
- [ ] https://github.com/stackabletech/hbase-operator/pull/421
```
