### ISSUE TITLE
CRD docs: polish epic

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#500]
The initial work to get generated docs up and running was done: https://github.com/stackabletech/documentation/issues/328

Now we need to fill the docs with content.

And then we need to update the CRD docs for all operators, similar to the druid PR: 

```[tasklist]
### Operators
- [ ] https://github.com/stackabletech/airflow-operator/pull/354/
- [ ] https://github.com/stackabletech/druid-operator/pull/494
- [ ] https://github.com/stackabletech/hbase-operator/pull/425
- [ ] https://github.com/stackabletech/hdfs-operator/pull/433
- [ ] https://github.com/stackabletech/hive-operator/pull/394
- [ ] https://github.com/stackabletech/kafka-operator/pull/645
- [ ] https://github.com/stackabletech/nifi-operator/pull/537
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/319
- [ ] https://github.com/stackabletech/superset-operator/pull/431
- [ ] https://github.com/stackabletech/trino-operator/pull/510
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/749
- [ ] https://github.com/stackabletech/commons-operator/pull/190
- [ ] https://github.com/stackabletech/secret-operator/pull/333
- [ ] https://github.com/stackabletech/listener-operator/pull/123
```

There is a style guide here: https://docs.stackable.tech/home/nightly/contributor/style-guide#_crd_documentation

Also, all the CRD docs should be linked under "Reference" in our regular docs.

```[tasklist]
### Products
- [ ] https://github.com/stackabletech/documentation/pull/509
- [ ] https://github.com/stackabletech/airflow-operator/pull/360
- [ ] https://github.com/stackabletech/druid-operator/pull/500
- [ ] https://github.com/stackabletech/hbase-operator/pull/433
- [ ] https://github.com/stackabletech/hdfs-operator/pull/446
- [ ] https://github.com/stackabletech/hive-operator/pull/398
- [ ] https://github.com/stackabletech/kafka-operator/pull/650
- [ ] https://github.com/stackabletech/nifi-operator/pull/546
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/332
- [ ] https://github.com/stackabletech/superset-operator/pull/438
- [ ] https://github.com/stackabletech/trino-operator/pull/516
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/754
- [ ] https://github.com/stackabletech/commons-operator/pull/192
- [ ] https://github.com/stackabletech/listener-operator/pull/130
- [ ] https://github.com/stackabletech/opa-operator/pull/499
- [ ] https://github.com/stackabletech/secret-operator/pull/338
```

also this: https://github.com/stackabletech/crddocs/issues/7

also this: https://github.com/stackabletech/documentation/issues/510

**Comment by adwk67** [comment]
stackablectl now uses `-c kind` instead of `-k` to create a kind cluster inline, and the cluster is a single node one. The getting started guides still refer to `-k` in some places.
