### ISSUE TITLE
Document that operators need to talk to their products

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#538]
As a user
I want to know about network connectivity requirements
so I can configure my k8s to make sure everything works.

Some operators need to connect to product APIs to configure the product, sometimes just for specific features. 
If a feature or operator needs access, this should be documented somewhere.
The exact location depends on why access is needed.

More specific advice on concrete NetworkPolicies is out of scope of this ticket, and instead will be tackled as part of this: https://github.com/stackabletech/issues/issues/449

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/nifi-operator/issues/562
- [ ] https://github.com/stackabletech/superset-operator/issues/445
- [ ] https://github.com/stackabletech/zookeeper-operator/issues/759
```

Besides the list above, not other operator connects to product pods.

## Acceptance criteria

- For all products it is documented when and why the operator talks to the product. If it is part of a specific feature, it is documented in the usage guide for that feature.
