### ISSUE TITLE
Add short note about image locations 

### ISSUE THREAD

**Issue by adwk67** [stackabletech/documentation#544]
For users that are considering using custom images based on our own images, it may be useful to have a short explanation as to where to find them i.e. in [this](https://docs.stackable.tech/home/stable/operators/supported_versions#_apache_spark_on_kubernetes).

```[tasklist]
### Tasks
- [x] update the product image selection page to better explain where to find base images for custom images: https://github.com/stackabletech/documentation/pull/567
- [x] link from the "Supported versions" page to product image selection/custom images: https://github.com/stackabletech/documentation/pull/569
```

```[tasklist]
### Update 'Supported versions' section in product operator docs
- [ ] https://github.com/stackabletech/airflow-operator/pull/413
- [ ] https://github.com/stackabletech/druid-operator/pull/540
- [ ] https://github.com/stackabletech/hbase-operator/pull/481
- [ ] https://github.com/stackabletech/hdfs-operator/pull/507
- [ ] https://github.com/stackabletech/hive-operator/pull/442
- [ ] https://github.com/stackabletech/kafka-operator/pull/687
- [ ] https://github.com/stackabletech/nifi-operator/pull/596
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/376
- [ ] https://github.com/stackabletech/superset-operator/pull/478
- [ ] https://github.com/stackabletech/trino-operator/pull/567
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/796
- [ ] https://github.com/stackabletech/opa-operator/pull/548
```

**Comment by fhennig** [comment]
I think I would like to instead add a tutorial: _How to run customized product images_ 

This tutorial should:
- explain where all the images are
- show how to use our images as base images
- show how to use this custom image in a Stacklet definition

maybe spark can be a good Stacklet to try this on, with adding some custom `jar` to it.

I would also link to the tutorial from [here](https://docs.stackable.tech/home/nightly/concepts/product-image-selection) and link back to this page as well.

In the [Supported versions](file:///home/felix/repos/documentation/build/site/home/nightly/spark-k8s/index.html#_supported_versions) section of the operators we can also link to the product image selection page, that should then send people on the right track.

opinions @lfrancke @adwk67 ?

**Comment by lfrancke** [comment]
Yes. A tutorial for this would be a great idea.

**Comment by adwk67** [comment]
Yes, I agree. That makes a lot of sense.

**Comment by fhennig** [comment]
Alright, so I've created a different ticket for the tutorial: https://github.com/stackabletech/documentation/issues/568

And for this one I simply want to link from the oeprators to the product image selection page, and update that page to more clearly explain where the base images are.

**Comment by fhennig** [comment]
all the task lists are done

**Comment by fhennig** [comment]
@adwk67 maybe you can have a look into the docs if you think this is improved! If not we can revisit this issue and maybe reopen it
