### ISSUE TITLE
Improve contributors guide

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#555]
As a user of the SDP I might want to contribute features, and for that I want to know the guidelines around contribution and how to set up a dev environment.

```[tasklist]
### Tasks
- [ ] make dedicated pages for "Contributing to an operator", "Contributing to documentation", "Contributing to product images"
- [ ] Make sure the [Steps to contribute](https://docs.stackable.tech/home/stable/contributor/steps) are still up to date. This page should proably be changed significantly
- [ ] https://github.com/stackabletech/documentation/issues/578
- [ ] https://github.com/stackabletech/operator-templating/issues/335
- [ ] https://github.com/stackabletech/secret-operator/issues/375
- [ ] https://github.com/stackabletech/listener-operator/issues/152
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/210
- [ ] https://github.com/stackabletech/image-tools/issues/10
- [ ] https://github.com/stackabletech/documentation/issues/556
- [ ] https://github.com/stackabletech/operator-templating/pull/354
```
