### ISSUE TITLE
tracking ticket: link feature tracker and GitHub operator repositories

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#588]
```[tasklist]
### Products
- [ ] https://github.com/stackabletech/airflow-operator/pull/420
- [ ] https://github.com/stackabletech/druid-operator/pull/543
- [ ] https://github.com/stackabletech/hbase-operator/pull/484
- [ ] https://github.com/stackabletech/hdfs-operator/pull/511
- [ ] https://github.com/stackabletech/hive-operator/pull/445
- [ ] https://github.com/stackabletech/kafka-operator/pull/691
- [ ] https://github.com/stackabletech/nifi-operator/pull/599
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/386
- [ ] https://github.com/stackabletech/superset-operator/pull/481
- [ ] https://github.com/stackabletech/trino-operator/pull/570
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/800
- [ ] https://github.com/stackabletech/opa-operator/pull/552
- [ ] https://github.com/stackabletech/secret-operator/pull/399
- [ ] https://github.com/stackabletech/commons-operator/pull/232
- [ ] https://github.com/stackabletech/listener-operator/pull/176
```

related:
- https://github.com/stackabletech/documentation/issues/548
- https://github.com/stackabletech/documentation/issues/412
