### ISSUE TITLE
Improve search result display

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#615]
Currently, multiple pages with the same title like "Security" or "Log aggregation" from different operators cannot be distinguished in the search results, this needs to be fixed. 

## Tasks

- [x] Switch from the default pagefind UI to the modular one
- [x] In the documentation-ui, tag the breadcrumbs [metadata](https://pagefind.app/docs/metadata/). There is a `breadcrumbs.hbs` file where it can be done.
- [x] Adjust the UI
- [x] Pin the pagefind version
- [x] Update prod UI

**Comment by fhennig** [comment]
links were not clickable, needs more work

**Comment by sbernauer** [comment]
feedback: Please focus on the search bar once clicked

**Comment by fhennig** [comment]
The searchbar focus will be a new issue. This one is actually resolved by this PR: https://github.com/stackabletech/documentation-ui/pull/67
